@startuml
hide empty description

skinparam titleBorderRoundCorner 5
skinparam titleBorderThickness 2
skinparam titleBorderColor black

title State Diagram - **OpenWinch**

header
Version 0.1.0 by Mickael Gaillard
endheader

center footer
Generated at %date("dd/MM/yyyy HH:mm")
OpenWinch © 2020-%date("yyyy")
endfooter

state isBoot {
    UNKNOWN: When system power up
}

[*] -right-> UNKNOWN
BOOTED: When system is booted
BOOTED: Display is enable and all function available
UNKNOWN --> BOOTED

state isInit {
    INIT: Initialize system (sensors & logic & actors)
    INIT: Initialize count rotation
}

BOOTED -left-> INIT : initialize()

state isStop {
    STOP: Motor is brake
    note left of STOP: Transition state
    IDLE: Power motor is Up
    STOP --> IDLE : stopped()
}

state isRun {
    START: Motor accelarate
    note left of START: Transition state
    RUNNING: Motor stabilize speed
    START --> RUNNING : started()
}

state isFault {
    ERROR: Power motor is Down
    ERROR -left-> INIT : initialize()
}

INIT -right-> IDLE : initialized()

isStop --> START : start()
'IDLE --> START : start()
'STOP -right-> START : start()

isRun -up-> STOP: stop()
'RUNNING --> STOP : stop()
'START -left-> STOP : stop()

isRun --> ERROR: emergency()
'START --> ERROR: emergency()
'RUNNING --> ERROR: emergency()

isStop --> ERROR: emergency()
'Stop --> ERROR: emergency()
'IDLE --> ERROR : emergency()

ERROR --> [*]

@enduml
